apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-iriwqyte
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-iriwqyte:7764291c2fcfc11f70d18cbde09392f31552718d@sha256:10f7aae6c4e7b1e80c77e71098e5fb35f4e472efe5869808d2fa3e8641bd7a00
        name: container-image  
